[tool.poetry]
name = "webx403-client"
version = "1.0.0"
description = "WebX403 Python Client SDK - Seamless Solana wallet authentication for Python applications"
authors = ["WebX403 Contributors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ByrgerBib/webx403"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"
solders = "^0.18.1"
base58 = "^2.1.1"
pynacl = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
